version: '3'

services:
  test:
    image: ghcr.io/salsadigitalauorg/ansible-test:latest
    volumes:
      - ./api:/usr/share/collections/ansible_collections/lagoon/api
    working_dir: /usr/share/collections/ansible_collections/lagoon/api
