"""Selection-shape guardrail for GraphQL documents.

Every GraphQL document this collection builds must be minimal, plus a
bounded nesting rule -- not a raw selection-set depth limit. A document
may select:

- any number of scalar/enum leaves at the top level;
- a **bounded object hop**: a single-valued object field, one level deep,
  whose own leaves are all scalar/enum;
- **one** collection (list) hop per document: a list-valued field, one
  level deep, whose own leaves are all scalar/enum;
- a **bounded scalar-leaf list beneath a single-valued hop**: one of a
  ``'single'``-kind hop's own leaves may itself be a list field, one
  level deeper, whose own leaves are all scalar/enum (e.g.
  ``autogeneratedRouteConfig { pathRoutes { fromService toService path
  } }``). Never permitted beneath a ``'list'``-kind hop -- that recursion
  is v1's actual defect and stays forbidden unconditionally. This nested
  list still counts toward the one-list-per-document cap below.

An object-typed leaf beneath any nested selection is forbidden -- that is
v1's actual defect (``environments { openshift { ... } }``), not merely a
depth number. A second list selection in the same document is forbidden
even if each, alone, would be permitted -- this is what stops a future
document reassembling v1's ``projectInfo`` breadth one field at a time.

Whether a given nesting field is *permitted* at all, and which kind (single
or list) and leaves it declares, is governed by an explicit registry
(:data:`PERMITTED_NESTED_SELECTIONS`) validated against the vendored SDL by
:func:`assert_registry_matches_sdl` -- the guard's own text-based parser has
no schema knowledge and cannot infer list-ness or leaf-object-ness on its
own.

This module is a **test-time helper**, not runtime code. It lives under
``tests/`` rather than ``plugins/`` deliberately and must not be
imported from anything under ``plugins/``.

It imports :class:`.module_utils.client.LagoonClient` to reconstruct
``build_query(...)`` call sites (see :func:`collect_candidate_documents`)
by calling the real implementation rather than re-deriving its
string-building logic here, which could drift from it. This is safe:
``client.py`` has no ``AnsibleModule`` dependency of its own, so this
stays a plain function call, never an ``import`` of an actual *module*
file under ``plugins/modules/`` (those require a constructed
``AnsibleModule`` to run at all).

Two layers, deliberately kept separate:

1. :func:`max_selection_depth` -- a character scanner (not a regex; brace
   nesting is not a regular language) that only detects a malformed
   document: unbalanced braces, or an unterminated string/block-string.
   It is aware of string literals and ``#`` comments so that braces
   appearing inside either are never mistaken for selection-set
   boundaries. It says nothing about shape.
2. :func:`parse_root_selection` / :func:`classify_selection_shape` -- a
   small recursive-descent parser building an actual selection tree,
   which :func:`assert_flat_query` classifies against the registry. This
   is what replaced the old raw depth ceiling (previously
   ``MAX_PERMITTED_DEPTH = 2``): depth alone cannot tell
   ``environments { id }`` (permitted) from ``environments { openshift {
   id } }`` (forbidden) -- both are the same depth.

SDL parsing (registry conformance) uses the standard library only --
``codegen/``'s ``graphql-core`` dependency must never reach the
environment that runs this test suite; a regex/brace scan over the
vendored SDL text is sufficient to answer "is this field list-typed"
and "is this leaf scalar/enum".
"""

from __future__ import (absolute_import, division, print_function)
__metaclass__ = type

import ast
import os
import re

from ansible_collections.salsadigitalauorg.lagoon.plugins.module_utils \
    .client import LagoonClient
from ansible_collections.salsadigitalauorg.lagoon.plugins.module_utils \
    .errors import LagoonConfigError

#: Matches a name assigned a GraphQL document, e.g. ``PROJECT_QUERY``,
#: ``ADD_PROJECT_MUTATION``, ``SOME_GQL``, ``FOO_DOCUMENT``.
_NAME_RE = re.compile(r'(?i)(QUERY|MUTATION|_GQL|DOCUMENT)')

#: Matches a string literal that looks like it *contains* a GraphQL
#: operation -- used to catch documents that are not conveniently named,
#: e.g. inline literals passed straight to ``client.execute(...)``.
_OPERATION_LITERAL_RE = re.compile(r'(query[\s(]|mutation[\s(])')

#: Ansible ``DOCUMENTATION``/``EXAMPLES``/``RETURN`` module-level string
#: constants are YAML prose, never GraphQL documents, even though their
#: names and content can incidentally match ``_NAME_RE`` (``RETURN``
#: contains no match, but ``DOCUMENTATION`` does) or
#: ``_OPERATION_LITERAL_RE`` (prose mentioning "the flat-query rule" or
#: similar contains "query " next to a brace). Both rules must skip
#: these constants and every string literal nested inside them, or the
#: sweep finds "documents" that were never GraphQL at all -- which
#: defeats the vacuous-pass guard: it would keep finding *something*
#: even with no GraphQL-producing code in the tree.
_DOC_CONSTANTS = frozenset({'DOCUMENTATION', 'EXAMPLES', 'RETURN'})

#: Placeholder recorded for a ``build_query(...)`` call site whose
#: arguments could not be fully statically resolved (e.g. ``fields``
#: built dynamically at runtime). It still counts toward the
#: vacuous-pass guard, but carries no document for
#: :func:`assert_flat_query` to check -- callers must skip the depth
#: assertion for this marker rather than pass it through as a document.
UNRESOLVED_BUILD_QUERY = '<build_query: unresolved arguments>'

#: Placeholder recorded for a ``build_query(...)`` call site whose
#: arguments resolve statically but that the real
#: :meth:`LagoonClient.build_query` itself rejects (e.g. an invalid
#: operation name) -- a call site guaranteed to fail at runtime. Unlike
#: :data:`UNRESOLVED_BUILD_QUERY`, this is not a "not checked" state:
#: callers must treat it as an unconditional violation.
INVALID_BUILD_QUERY = '<build_query: invalid arguments>'

#: Placeholder recorded for a call site named ``build_query`` that the
#: sweep cannot prove resolves to the real
#: :meth:`LagoonClient.build_query` -- a locally defined/assigned
#: ``build_query`` that shadows the real one, or an import from
#: somewhere other than ``module_utils.client``. Reconstructing such a
#: call site by invoking the real implementation would silently check
#: the wrong function's output. Callers must treat this as an
#: unconditional violation: a shadowed ``build_query`` inside
#: ``plugins/`` is itself a defect worth failing the sweep over.
SHADOWED_BUILD_QUERY = '<build_query: shadowed, not the real implementation>'


class QueryDepthError(ValueError):
    """Raised when a document has unbalanced braces or an unterminated
    string/comment -- i.e. the scanner cannot compute a depth at all."""


class ShapeViolation(ValueError):
    """Raised by :func:`classify_selection_shape` when a parsed selection
    tree violates the nesting rule. ``reason`` is a short machine-checkable
    tag so a test can assert *which* rule fired, not just that one did.
    """

    def __init__(self, reason, message):
        self.reason = reason
        super(ShapeViolation, self).__init__(message)


def max_selection_depth(document):
    """Return the maximum GraphQL selection-set nesting depth in
    ``document``.

    A character scanner, not a regex: tracks brace depth while skipping
    over string literals (``"..."`` and block strings ``\"\"\"...\"\"\"``,
    including ``\\"`` escapes) and ``#`` comments to end of line, so that
    braces appearing inside either are never mistaken for selection-set
    boundaries.

    Raises :class:`QueryDepthError` (a :class:`ValueError`) if the braces
    are unbalanced, or if a string literal or block string is left
    unterminated -- both indicate a malformed document worth surfacing,
    not something to silently score as depth 0.
    """
    depth = 0
    max_depth = 0
    i = 0
    n = len(document)

    while i < n:
        ch = document[i]

        if ch == '#':
            newline = document.find('\n', i)
            i = n if newline == -1 else newline + 1
            continue

        if ch == '"':
            if document[i:i + 3] == '"""':
                end = document.find('"""', i + 3)
                if end == -1:
                    raise QueryDepthError(
                        "unterminated block string (triple-quote) "
                        "starting at position %d" % i)
                i = end + 3
                continue
            j = i + 1
            closed = False
            while j < n:
                if document[j] == '\\':
                    j += 2
                    continue
                if document[j] == '"':
                    closed = True
                    j += 1
                    break
                j += 1
            if not closed:
                raise QueryDepthError(
                    "unterminated string literal starting at position %d"
                    % i)
            i = j
            continue

        if ch == '{':
            depth += 1
            if depth > max_depth:
                max_depth = depth
            i += 1
            continue

        if ch == '}':
            depth -= 1
            if depth < 0:
                raise QueryDepthError(
                    "unbalanced braces: unexpected '}' at position %d" % i)
            i += 1
            continue

        i += 1

    if depth != 0:
        raise QueryDepthError(
            "unbalanced braces: %d unclosed '{' remaining" % depth)

    return max_depth


#: Parent type -> nesting field -> (kind, permitted leaves).
#: ``kind`` is ``'single'`` for a single-valued object hop or ``'list'``
#: for a collection hop -- checked against the SDL by
#: :func:`assert_registry_matches_sdl`, never assumed from the call site.
#: A nested selection is permitted only if its nesting field appears here,
#: with only the declared leaves selected beneath it, and at most one
#: ``'list'``-kind entry used per document (see
#: :func:`classify_selection_shape`). Adding an entry is a reviewable diff,
#: not an emergent property of a scanner.
#:
#: A leaf is normally a plain scalar/enum field name. Beneath a
#: ``'single'``-kind entry only, a leaf may instead be a single-entry
#: mapping ``{field: ('list', (leaf, ...))}`` declaring a bounded
#: scalar-leaf list one level deeper still -- e.g.
#: ``autogeneratedRouteConfig``'s ``pathRoutes``. This nested-list form is
#: never valid beneath a ``'list'``-kind entry: that recursion is v1's
#: actual defect and stays forbidden unconditionally.
PERMITTED_NESTED_SELECTIONS = {
    'Project': {
        'openshift': ('single', ('id', 'name')),
        'kubernetes': ('single', ('id', 'name')),
        'autogeneratedRouteConfig': ('single', (
            'enabled', 'allowPullRequests', 'prefixes',
            'disableRequestVerification',
            {'pathRoutes': ('list', (
                'fromService', 'toService', 'path'))})),
        'organizationDetails': ('single', ('id', 'name')),
        'environments': ('list', (
            'id', 'name', 'environmentType',
            'kubernetesNamespaceName', 'deployType', 'autoIdle')),
    },
    'Environment': {
        'project': ('single', ('id', 'name')),
        'openshift': ('single', ('id', 'name')),
        'kubernetes': ('single', ('id', 'name')),
        'autogeneratedRouteConfig': ('single', (
            'enabled', 'allowPullRequests', 'prefixes',
            'disableRequestVerification',
            {'pathRoutes': ('list', (
                'fromService', 'toService', 'path'))})),
    },
}


class _Selection:
    """One parsed field selection. ``sub`` is a list of child
    :class:`_Selection` (a nested selection set), or ``None`` for a leaf.
    """

    __slots__ = ('name', 'sub')

    def __init__(self, name, sub=None):
        self.name = name
        self.sub = sub


_IDENT_CHAR_RE = re.compile(r'[A-Za-z0-9_]')


def _skip_string_or_comment(document, i):
    """If ``document[i]`` begins a ``#`` comment or a string/block-string
    literal, return the index just past it. Otherwise return ``i``
    unchanged. Shared by the selection parser so it ignores braces,
    parentheses and identifiers inside either, exactly as
    :func:`max_selection_depth` already does.
    """
    n = len(document)
    ch = document[i]
    if ch == '#':
        newline = document.find('\n', i)
        return n if newline == -1 else newline + 1
    if ch == '"':
        if document[i:i + 3] == '"""':
            end = document.find('"""', i + 3)
            if end == -1:
                raise QueryDepthError(
                    "unterminated block string (triple-quote) starting "
                    "at position %d" % i)
            return end + 3
        j = i + 1
        while j < n:
            if document[j] == '\\':
                j += 2
                continue
            if document[j] == '"':
                return j + 1
            j += 1
        raise QueryDepthError(
            "unterminated string literal starting at position %d" % i)
    return i


def _skip_trivia(document, i):
    """Advance past whitespace, commas, comments and string literals --
    everything that can separate two selection-set tokens but carries no
    shape information of its own.
    """
    n = len(document)
    while i < n:
        ch = document[i]
        if ch.isspace() or ch == ',':
            i += 1
            continue
        if ch in ('#', '"'):
            new_i = _skip_string_or_comment(document, i)
            if new_i != i:
                i = new_i
                continue
        break
    return i


def _skip_arguments(document, i):
    """``document[i] == '('``. Return the index just past the matching
    ``')'``, tolerant of string literals containing parentheses.
    """
    n = len(document)
    depth = 0
    while i < n:
        ch = document[i]
        if ch == '"':
            i = _skip_string_or_comment(document, i)
            continue
        if ch == '(':
            depth += 1
            i += 1
            continue
        if ch == ')':
            depth -= 1
            i += 1
            if depth == 0:
                return i
            continue
        i += 1
    raise QueryDepthError("unterminated argument list starting search")


def _parse_selection_set(document, i):
    """``document[i] == '{'``. Returns ``(selections, end_index)`` where
    ``end_index`` is just past the matching ``'}'``.
    """
    n = len(document)
    i += 1
    selections = []
    while True:
        i = _skip_trivia(document, i)
        if i >= n:
            raise QueryDepthError("unterminated selection set")
        if document[i] == '}':
            return selections, i + 1
        j = i
        while j < n and _IDENT_CHAR_RE.match(document[j]):
            j += 1
        if j == i:
            raise QueryDepthError(
                "expected a field name at position %d" % i)
        name = document[i:j]
        i = _skip_trivia(document, j)
        if i < n and document[i] == '(':
            i = _skip_arguments(document, i)
            i = _skip_trivia(document, i)
        if i < n and document[i] == '{':
            sub_selections, i = _parse_selection_set(document, i)
            selections.append(_Selection(name, sub_selections))
        else:
            selections.append(_Selection(name, None))


def parse_root_selection(document):
    """Parse ``document`` and return the selection list one level below
    the operation's single root field -- i.e. the fields selected on
    ``projectByName(...)`` in
    ``query ($name: String!) { projectByName(name: $name) { id name } }``
    -- or ``None`` if the root call has no selection set at all (a bare
    scalar return, e.g. ``deleteProject``).

    Raises :class:`QueryDepthError` if the document has no selection set,
    or its root selection set does not contain exactly one field --
    every document this collection builds calls exactly one root
    operation.
    """
    n = len(document)
    i = 0
    while i < n and document[i] != '{':
        if document[i] in ('"', '#'):
            i = _skip_string_or_comment(document, i)
            continue
        i += 1
    if i >= n:
        raise QueryDepthError("no operation selection set found")
    root_selections, _end = _parse_selection_set(document, i)
    if len(root_selections) != 1:
        raise QueryDepthError(
            "expected exactly one root field selection, found %d" %
            len(root_selections))
    return root_selections[0].sub


def _split_leaf_declarations(permitted_leaves):
    """Split ``permitted_leaves`` (one nesting field's declared leaves)
    into ``(scalar_leaf_names, nested_list_leaves)``: a set of plain
    scalar/enum leaf names, and a ``{leaf_name: inner_leaves}`` map for
    any entry declaring a bounded scalar-leaf list one level deeper (see
    :data:`PERMITTED_NESTED_SELECTIONS`'s docstring).
    """
    scalar_leaf_names = set()
    nested_list_leaves = {}
    for entry in permitted_leaves:
        if isinstance(entry, dict):
            leaf_name, (_leaf_kind, inner_leaves) = next(iter(entry.items()))
            nested_list_leaves[leaf_name] = inner_leaves
        else:
            scalar_leaf_names.add(entry)
    return scalar_leaf_names, nested_list_leaves


def classify_selection_shape(selections, parent_type, registry=None):
    """Raise :class:`ShapeViolation` if ``selections`` (the selection list
    one level below the document's root field, as returned by
    :func:`parse_root_selection`) violates the nesting rule. Returns
    ``None`` on success.

    ``parent_type`` names the SDL type the root field returns (e.g.
    ``'Project'`` for ``projectByName``), used to look up which nested
    fields are permitted in ``registry`` (default
    :data:`PERMITTED_NESTED_SELECTIONS`).

    Enforces, in order:

    - every nested (non-leaf) selection's field name is declared in the
      registry for ``parent_type`` (``reason='undeclared_nesting'``);
    - every leaf beneath a nested selection is one of that entry's
      declared leaves, and is itself a plain leaf -- unless the nesting
      field is ``'single'``-kind and the leaf's name is declared as a
      nested list, in which case exactly one further level of scalar/enum
      leaves is permitted (``reason='object_leaf_beneath_nesting'``
      otherwise, including a nested list declared beneath a
      ``'list'``-kind nesting field -- that recursion stays forbidden
      unconditionally, regardless of what the registry declares);
    - at most one ``'list'``-kind nested selection appears in the
      document, counting a permitted nested list toward the same cap
      (``reason='multiple_list_selections'``).

    A document with no nested selections at all (every selection is a
    plain leaf) always passes -- this is the common case and needs no
    registry lookup.
    """
    if selections is None:
        return None

    permitted = (registry or PERMITTED_NESTED_SELECTIONS).get(
        parent_type, {})
    list_selections_seen = []

    for selection in selections:
        if selection.sub is None:
            continue

        if selection.name not in permitted:
            raise ShapeViolation(
                'undeclared_nesting',
                "field '%s' has a nested selection but is not declared "
                "in PERMITTED_NESTED_SELECTIONS for parent type '%s'" %
                (selection.name, parent_type))

        kind, permitted_leaves = permitted[selection.name]
        scalar_leaf_names, nested_list_leaves = _split_leaf_declarations(
            permitted_leaves)

        for leaf in selection.sub:
            if leaf.sub is not None:
                if kind != 'single' or leaf.name not in nested_list_leaves:
                    raise ShapeViolation(
                        'object_leaf_beneath_nesting',
                        "field '%s' beneath nested selection '%s' has "
                        "its own selection set -- an object leaf beneath "
                        "a nested selection is forbidden" %
                        (leaf.name, selection.name))
                inner_leaves = nested_list_leaves[leaf.name]
                for inner_leaf in leaf.sub:
                    if inner_leaf.sub is not None:
                        raise ShapeViolation(
                            'object_leaf_beneath_nesting',
                            "field '%s' beneath nested list '%s.%s' has "
                            "its own selection set -- nesting is "
                            "permitted two levels only" %
                            (inner_leaf.name, selection.name, leaf.name))
                    if inner_leaf.name not in inner_leaves:
                        raise ShapeViolation(
                            'undeclared_leaf',
                            "leaf '%s' beneath nested list '%s.%s' is "
                            "not one of its declared leaves %r" %
                            (inner_leaf.name, selection.name, leaf.name,
                             inner_leaves))
                list_selections_seen.append(
                    '%s.%s' % (selection.name, leaf.name))
                continue

            if leaf.name not in scalar_leaf_names:
                raise ShapeViolation(
                    'undeclared_leaf',
                    "leaf '%s' beneath nested selection '%s' is not one "
                    "of its declared leaves %r" %
                    (leaf.name, selection.name, scalar_leaf_names))

        if kind == 'list':
            list_selections_seen.append(selection.name)

    if len(list_selections_seen) > 1:
        raise ShapeViolation(
            'multiple_list_selections',
            "document selects more than one list-valued nested field "
            "in the same document: %r -- at most one collection hop is "
            "permitted per document" % (list_selections_seen,))

    return None


def assert_flat_query(document, source=None, parent_type=None,
                       registry=None):
    """Raise :class:`AssertionError` if ``document`` violates the
    selection-shape rule: unminimal, an object leaf beneath a nested
    selection, more than one list selection per document, or a nested
    field not declared in ``registry``.

    ``source`` -- typically ``"<path>:<name-or-lineno>"`` -- is included
    in the failure output so a sweep failure names the offending file and
    symbol, not just the document text. ``parent_type`` names the SDL
    type the document's root field returns, for registry lookup;
    omitted (``None``) for documents with no nested selections, where no
    lookup is needed.

    ``max_selection_depth`` still runs first: an unbalanced or
    unterminated document is a malformed-document error, not a shape
    violation, and is left to raise :class:`QueryDepthError` (a
    :class:`ValueError`) rather than :class:`AssertionError`.
    """
    max_selection_depth(document)
    root_selections = parse_root_selection(document)
    try:
        classify_selection_shape(root_selections, parent_type, registry)
    except ShapeViolation as e:
        where = " in %s" % source if source else ""
        raise AssertionError(
            "GraphQL document%s violates the selection-shape rule "
            "(%s): %s:\n%s" % (where, e.reason, e, document))


def _strip_sdl_descriptions(text):
    return re.sub(r'""".*?"""', '', text, flags=re.DOTALL)


def _strip_sdl_field_arguments(text):
    """Collapse every parenthesised argument list to ``()`` so the field
    regex below does not have to parse GraphQL argument syntax -- only
    field name and return type matter for conformance checking.
    Tolerant of parentheses inside string-literal default values.
    """
    result = []
    i, n = 0, len(text)
    while i < n:
        ch = text[i]
        if ch == '"':
            j = i + 1
            while j < n and text[j] != '"':
                j += 2 if text[j] == '\\' else 1
            j = min(j + 1, n)
            result.append(text[i:j])
            i = j
            continue
        if ch == '(':
            depth = 1
            i += 1
            while i < n and depth > 0:
                if text[i] == '(':
                    depth += 1
                elif text[i] == ')':
                    depth -= 1
                i += 1
            result.append('()')
            continue
        result.append(ch)
        i += 1
    return ''.join(result)


def _extract_sdl_type_block(sdl_text, type_name):
    """Return the full ``type <type_name> { ... }`` block (including an
    ``implements ...`` clause, if any) from ``sdl_text``, brace-balanced
    and aware of string/block-string literals. ``None`` if not found.
    """
    pattern = re.compile(
        r'(?:^|\n)type %s(?:\s+implements\s+[A-Za-z_][\w&\s]*)?\s*\{' %
        re.escape(type_name))
    m = pattern.search(sdl_text)
    if not m:
        return None
    start = sdl_text.index('{', m.start())
    i, depth, n = start, 0, len(sdl_text)
    while i < n:
        if sdl_text[i:i + 3] == '"""':
            end = sdl_text.find('"""', i + 3)
            i = (end + 3) if end != -1 else n
            continue
        ch = sdl_text[i]
        if ch == '"':
            j = i + 1
            while j < n and sdl_text[j] != '"':
                j += 2 if sdl_text[j] == '\\' else 1
            i = j + 1
            continue
        if ch == '{':
            depth += 1
            i += 1
            continue
        if ch == '}':
            depth -= 1
            i += 1
            if depth == 0:
                return sdl_text[start:i]
            continue
        i += 1
    return None


_SDL_FIELD_RE = re.compile(
    r'^\s*([A-Za-z_]\w*)\s*(?:\(\))?\s*:\s*(\[?[A-Za-z_]\w*\]?!?)',
    re.MULTILINE)


def sdl_object_type_fields(sdl_text, type_name):
    """Return ``{field_name: raw_type_string}`` for every field declared
    directly on ``type type_name { ... }`` in ``sdl_text`` (not
    inherited from an interface). ``None`` if the type is not found.
    ``raw_type_string`` keeps the SDL's own list/``!`` markers, e.g.
    ``'[EnvKeyValue]'``, ``'String!'``.
    """
    block = _extract_sdl_type_block(sdl_text, type_name)
    if block is None:
        return None
    clean = _strip_sdl_field_arguments(_strip_sdl_descriptions(block))
    fields = {}
    for m in _SDL_FIELD_RE.finditer(clean):
        fields[m.group(1)] = m.group(2)
    return fields


_SDL_SCALAR_RE = re.compile(r'(?:^|\n)scalar\s+([A-Za-z_]\w*)')
_SDL_ENUM_RE = re.compile(r'(?:^|\n)enum\s+([A-Za-z_]\w*)\s*\{')

#: GraphQL's own built-in scalars, always legal leaves regardless of
#: whether the vendored SDL declares them again.
_BUILTIN_SCALARS = frozenset({'Int', 'String', 'Boolean', 'Float', 'ID'})


def sdl_scalar_and_enum_names(sdl_text):
    """Return the set of every scalar (built-in plus ``scalar X``
    declarations) and enum type name declared in ``sdl_text`` -- the set
    of type names legal as a plain leaf with no selection set.
    """
    names = set(_BUILTIN_SCALARS)
    names.update(m.group(1) for m in _SDL_SCALAR_RE.finditer(sdl_text))
    names.update(m.group(1) for m in _SDL_ENUM_RE.finditer(sdl_text))
    return names


def _assert_leaf_is_scalar_or_enum(nested_fields_map, nested_type_name,
                                    leaf, scalar_and_enum_names, label):
    if leaf not in nested_fields_map:
        raise AssertionError(
            "registry leaf '%s' under '%s' does not exist on SDL type "
            "'%s'" % (leaf, label, nested_type_name))
    leaf_raw_type = nested_fields_map[leaf]
    leaf_type_name = leaf_raw_type.strip('[]!')
    if leaf_type_name not in scalar_and_enum_names:
        raise AssertionError(
            "registry leaf '%s.%s' has SDL type '%s', which is not a "
            "scalar or enum -- an object leaf beneath a nested "
            "selection would reintroduce the fan-out this rule exists "
            "to forbid" % (label, leaf, leaf_raw_type))


def assert_registry_matches_sdl(sdl_text, registry=None):
    """Raise :class:`AssertionError` if any entry in ``registry``
    (default :data:`PERMITTED_NESTED_SELECTIONS`) does not conform to
    ``sdl_text``:

    - the parent type and nesting field both exist;
    - the declared ``kind`` (``'single'``/``'list'``) matches the SDL's
      actual list-ness for that field;
    - every declared leaf exists on the nested field's own type and is
      itself scalar/enum (never an object) -- this is what stops the
      registry drifting into permitting the exact fan-out the rule
      exists to forbid;
    - a leaf declared as a nested list (``{field: ('list', (leaf, ...))}``,
      permitted only beneath a ``'single'``-kind entry) is itself a real
      list field on the nesting field's own SDL type, and every one of
      *its* declared leaves is scalar/enum in turn -- a third level of
      nesting is rejected outright rather than validated.
    """
    registry = registry or PERMITTED_NESTED_SELECTIONS
    scalar_and_enum_names = sdl_scalar_and_enum_names(sdl_text)

    for parent_type, nested_fields in registry.items():
        parent_fields = sdl_object_type_fields(sdl_text, parent_type)
        if parent_fields is None:
            raise AssertionError(
                "registry parent type '%s' does not exist in the SDL" %
                parent_type)

        for nesting_field, (kind, leaves) in nested_fields.items():
            if nesting_field not in parent_fields:
                raise AssertionError(
                    "registry field '%s.%s' does not exist in the SDL" %
                    (parent_type, nesting_field))

            raw_type = parent_fields[nesting_field]
            is_list_in_sdl = raw_type.startswith('[')
            sdl_kind = 'list' if is_list_in_sdl else 'single'
            if sdl_kind != kind:
                raise AssertionError(
                    "registry declares '%s.%s' as kind=%r but the SDL "
                    "declares it as a %s type (%r)" %
                    (parent_type, nesting_field, kind, sdl_kind, raw_type))

            nested_type_name = raw_type.strip('[]!')
            nested_fields_map = sdl_object_type_fields(
                sdl_text, nested_type_name)
            if nested_fields_map is None:
                raise AssertionError(
                    "registry field '%s.%s' points at type '%s', which "
                    "has no SDL object-type definition to validate "
                    "leaves against" %
                    (parent_type, nesting_field, nested_type_name))

            label = '%s.%s' % (parent_type, nesting_field)
            for leaf in leaves:
                if isinstance(leaf, dict):
                    inner_field, (inner_kind, inner_leaves) = next(
                        iter(leaf.items()))
                    if kind != 'single':
                        raise AssertionError(
                            "registry declares a nested list leaf '%s' "
                            "under '%s', but '%s' is kind='list' -- a "
                            "nested list is only permitted beneath a "
                            "'single'-kind entry" %
                            (inner_field, label, label))
                    if inner_field not in nested_fields_map:
                        raise AssertionError(
                            "registry nested list leaf '%s' under '%s' "
                            "does not exist on SDL type '%s'" %
                            (inner_field, label, nested_type_name))
                    inner_raw_type = nested_fields_map[inner_field]
                    inner_sdl_kind = (
                        'list' if inner_raw_type.startswith('[')
                        else 'single')
                    if inner_sdl_kind != inner_kind:
                        raise AssertionError(
                            "registry declares '%s.%s' as kind=%r but "
                            "the SDL declares it as a %s type (%r)" %
                            (label, inner_field, inner_kind,
                             inner_sdl_kind, inner_raw_type))
                    inner_type_name = inner_raw_type.strip('[]!')
                    inner_fields_map = sdl_object_type_fields(
                        sdl_text, inner_type_name)
                    if inner_fields_map is None:
                        raise AssertionError(
                            "registry nested list leaf '%s.%s' points "
                            "at type '%s', which has no SDL object-type "
                            "definition to validate leaves against" %
                            (label, inner_field, inner_type_name))
                    inner_label = '%s.%s' % (label, inner_field)
                    for inner_leaf in inner_leaves:
                        if isinstance(inner_leaf, dict):
                            raise AssertionError(
                                "registry declares a further nested "
                                "selection %r beneath '%s' -- nesting is "
                                "permitted two levels only, and a third "
                                "level would reintroduce the fan-out "
                                "this rule exists to forbid" %
                                (inner_leaf, inner_label))
                        _assert_leaf_is_scalar_or_enum(
                            inner_fields_map, inner_type_name, inner_leaf,
                            scalar_and_enum_names, inner_label)
                    continue

                _assert_leaf_is_scalar_or_enum(
                    nested_fields_map, nested_type_name, leaf,
                    scalar_and_enum_names, label)


def _iter_python_files(root_dir):
    for dirpath, dirnames, filenames in os.walk(root_dir):
        dirnames[:] = [d for d in dirnames if d != '__pycache__']
        for filename in sorted(filenames):
            if filename.endswith('.py'):
                yield os.path.join(dirpath, filename)


def _module_and_class_level_assigns(tree):
    """Yield ``(name, value, lineno)`` for every string-constant assignment
    to a plain name that appears directly in a module body or a class
    body -- deliberately *not* inside a function/method body, since a
    GraphQL document is always built and named at that scope, never
    inside a function.
    """
    results = []

    def _scan_body(body):
        for stmt in body:
            if isinstance(stmt, ast.Assign):
                value = stmt.value
                if isinstance(value, ast.Constant) and \
                        isinstance(value.value, str):
                    for target in stmt.targets:
                        if isinstance(target, ast.Name):
                            results.append(
                                (target.id, value.value, stmt.lineno))
            if isinstance(stmt, ast.ClassDef):
                _scan_body(stmt.body)

    _scan_body(tree.body)
    return results


def _literal_from_ast(node):
    """Return the plain Python value ``node`` represents if -- and only
    if -- it is fully built from :class:`ast.Constant` leaves (nested
    inside, at most, ``ast.List``/``ast.Tuple``/``ast.Dict``).

    Raises :class:`ValueError` for anything else (a name reference, a
    function call, a comprehension, an f-string, ...) so the caller can
    treat the containing ``build_query(...)`` invocation as not fully
    statically resolvable, rather than silently resolving to a wrong or
    partial value.
    """
    if isinstance(node, ast.Constant):
        return node.value
    if isinstance(node, ast.List):
        return [_literal_from_ast(elt) for elt in node.elts]
    if isinstance(node, ast.Tuple):
        return tuple(_literal_from_ast(elt) for elt in node.elts)
    if isinstance(node, ast.Dict):
        if any(k is None for k in node.keys):
            # A ``**spread`` entry -- not a literal key/value pair.
            raise ValueError("dict contains a non-literal spread entry")
        return {
            _literal_from_ast(k): _literal_from_ast(v)
            for k, v in zip(node.keys, node.values)
        }
    raise ValueError("not a statically resolvable literal: %r" % (node,))


def _is_build_query_call(node):
    """True if ``node`` is a call to something named ``build_query`` --
    either the attribute form (``<expr>.build_query(...)``) or the bare
    form (``build_query(...)``).

    This only tests the *name* -- it says nothing about whether the
    callee is actually :meth:`LagoonClient.build_query`. Use
    :func:`_call_is_trusted_build_query` to decide whether reconstructing
    the call by invoking the real implementation is safe; a call site
    can match this function and still turn out to be shadowed.
    """
    func = node.func
    if isinstance(func, ast.Attribute):
        return func.attr == 'build_query'
    if isinstance(func, ast.Name):
        return func.id == 'build_query'
    return False


def _names_bound_to_lagoon_client(tree):
    """Return the set of local names bound, anywhere in ``tree``, to the
    real ``LagoonClient`` class via either
    ``from ...module_utils.client import LagoonClient [as X]`` (the
    absolute-import shape every ``plugins/modules/`` and
    ``plugins/action/`` file uses) or ``from .client import LagoonClient
    [as X]`` (the sibling-relative shape a file living inside
    ``module_utils/`` itself uses, per every other cross-file import in
    that package -- see ``auth.py``'s ``from .errors import ...``).

    Only these two import shapes are trusted -- a name that merely
    *looks* like it holds ``LagoonClient`` (e.g. reassigned later, or
    imported from somewhere else entirely) is not, and any
    ``build_query`` reached through it must be treated as shadowed
    rather than reconstructed via the real implementation.
    """
    names = set()
    for node in ast.walk(tree):
        if not isinstance(node, ast.ImportFrom):
            continue
        is_absolute_client_import = \
            node.module and node.module.endswith('module_utils.client')
        is_sibling_client_import = \
            node.level == 1 and node.module == 'client'
        if is_absolute_client_import or is_sibling_client_import:
            for alias in node.names:
                if alias.name == 'LagoonClient':
                    names.add(alias.asname or alias.name)
    return names


def _names_bound_to_build_query(tree, trusted_client_names):
    """Return the set of local names bound, anywhere in ``tree``, to the
    real ``LagoonClient.build_query`` via a plain alias assignment
    (``build_query = LagoonClient.build_query``, where ``LagoonClient``
    is itself one of ``trusted_client_names``).

    Any other name called as ``build_query(...)`` -- a local ``def``, a
    ``lambda``, a class, or an import from anywhere else -- is not
    trusted, and the bare-form call site must be recorded as shadowed
    rather than reconstructed via the real implementation.
    """
    names = set()
    for node in ast.walk(tree):
        if not isinstance(node, ast.Assign):
            continue
        value = node.value
        if isinstance(value, ast.Attribute) and value.attr == 'build_query' \
                and isinstance(value.value, ast.Name) \
                and value.value.id in trusted_client_names:
            for target in node.targets:
                if isinstance(target, ast.Name):
                    names.add(target.id)
    return names


def _call_is_trusted_build_query(node, trusted_client_names,
                                  trusted_bare_names):
    """True if ``node`` -- already known to be named ``build_query`` by
    :func:`_is_build_query_call` -- provably resolves to the real
    :meth:`LagoonClient.build_query`, and can therefore be safely
    reconstructed by invoking that real implementation.
    """
    func = node.func
    if isinstance(func, ast.Attribute):
        return isinstance(func.value, ast.Name) and \
            func.value.id in trusted_client_names
    if isinstance(func, ast.Name):
        return func.id in trusted_bare_names
    return False


def _resolve_build_query_args(node):
    """Resolve ``node`` (a call to ``build_query``) to the
    ``(operation, kwargs)`` pair :meth:`LagoonClient.build_query` would
    receive at runtime.

    Raises :class:`ValueError` if any argument is not fully statically
    resolvable (dynamic ``fields``, a variable, a comprehension, a
    ``*args``/``**kwargs`` spread, ...) or if the call shape omits a
    required argument -- callers must record such a call site as
    unresolved rather than dropping it, so it still counts toward the
    vacuous-pass guard while making the "not checked" state visible
    rather than silent.
    """
    if any(isinstance(a, ast.Starred) for a in node.args):
        raise ValueError("*args spread is not statically resolvable")

    kwargs = {}
    for keyword in node.keywords:
        if keyword.arg is None:
            raise ValueError("**kwargs spread is not statically resolvable")
        kwargs[keyword.arg] = _literal_from_ast(keyword.value)

    positional = [_literal_from_ast(arg) for arg in node.args]

    if positional:
        if 'operation' in kwargs:
            raise ValueError("operation given both positionally and "
                              "by keyword")
        operation = positional[0]
        positional = positional[1:]
    else:
        operation = kwargs.pop('operation', None)

    if operation is None or positional:
        # No operation resolved, or unexpected extra positional args --
        # not a call shape build_query() actually accepts.
        raise ValueError("no resolvable operation, or unexpected extra "
                          "positional arguments")

    if 'fields' not in kwargs:
        # fields is a required keyword-only argument on the real
        # signature; a call site omitting it cannot be reconstructed by
        # calling build_query() (it would raise TypeError), so treat it
        # as unresolved rather than letting that exception escape the
        # sweep.
        raise ValueError("fields is required and was not supplied")

    return operation, kwargs


def _reconstruct_build_query_call(node):
    """Reconstruct the GraphQL document a trusted ``build_query(...)``
    call site would produce at runtime.

    Returns one of: the reconstructed document string; or
    :data:`UNRESOLVED_BUILD_QUERY` if the arguments are not fully
    statically resolvable; or :data:`INVALID_BUILD_QUERY` if the
    arguments resolve but the real :meth:`LagoonClient.build_query`
    itself rejects them (e.g. an invalid operation name) -- a call site
    guaranteed to fail at runtime, and therefore an unconditional
    violation, not merely "not checked".
    """
    try:
        operation, kwargs = _resolve_build_query_args(node)
    except ValueError:
        return UNRESOLVED_BUILD_QUERY

    try:
        return LagoonClient.build_query(operation, **kwargs)
    except (LagoonConfigError, TypeError):
        return INVALID_BUILD_QUERY


def _build_query_call_sites(tree, path):
    """Yield ``(source_label, document)`` for every call site named
    ``build_query`` in ``tree``.

    A call that provably resolves to the real
    :meth:`LagoonClient.build_query` (see
    :func:`_call_is_trusted_build_query`) is reconstructed via
    :func:`_reconstruct_build_query_call`, which may itself yield
    :data:`UNRESOLVED_BUILD_QUERY` or :data:`INVALID_BUILD_QUERY` in
    place of a document.

    A call that is *not* provably the real implementation -- a locally
    defined/assigned ``build_query`` that shadows it, or an import from
    anywhere else -- is yielded as :data:`SHADOWED_BUILD_QUERY` without
    ever being reconstructed: doing so would silently check a document
    the shadowing code will never actually produce.
    """
    trusted_client_names = _names_bound_to_lagoon_client(tree)
    trusted_bare_names = _names_bound_to_build_query(
        tree, trusted_client_names)

    for node in ast.walk(tree):
        if not isinstance(node, ast.Call) or not _is_build_query_call(node):
            continue
        lineno = getattr(node, 'lineno', '?')
        label = '%s:%s' % (path, lineno)
        if not _call_is_trusted_build_query(
                node, trusted_client_names, trusted_bare_names):
            yield (label, SHADOWED_BUILD_QUERY)
        else:
            yield (label, _reconstruct_build_query_call(node))


def _doc_constant_value_node_ids(tree):
    """Return the set of ``id()`` for every AST node nested inside the
    value of a module-level ``DOCUMENTATION``/``EXAMPLES``/``RETURN``
    assignment (see :data:`_DOC_CONSTANTS`), so rule 2 below can skip
    every string literal that lives inside one of these YAML doc blocks,
    not just the top-level constant itself.
    """
    ids = set()
    for node in ast.walk(tree):
        if not isinstance(node, ast.Assign):
            continue
        for target in node.targets:
            if isinstance(target, ast.Name) and target.id in _DOC_CONSTANTS:
                for sub in ast.walk(node.value):
                    ids.add(id(sub))
    return ids


def collect_candidate_documents(root_dir):
    """Walk every ``.py`` file under ``root_dir`` via :mod:`ast` (never
    ``import``, which would pull in ``AnsibleModule`` and fail under bare
    pytest) and return a list of ``(source_label, document)`` pairs for
    every string that looks like it might be a GraphQL document:

    1. Every module-level or class-level string constant assigned to a
       name matching ``(?i)(QUERY|MUTATION|_GQL|DOCUMENT)``, excluding
       :data:`_DOC_CONSTANTS`.
    2. Every string literal anywhere in the file that contains both ``{``
       and one of ``query ``/``mutation ``/``query(``/``mutation(``,
       excluding any literal nested inside a :data:`_DOC_CONSTANTS`
       assignment.
    3. Every call site named ``build_query`` (attribute form
       ``LagoonClient.build_query(...)``, or bare ``build_query(...)``
       via a plain alias). One that provably resolves to the real
       :meth:`LagoonClient.build_query` is reconstructed by calling that
       real implementation with its statically-resolved arguments, and
       may itself be paired with a placeholder instead of a document:
       :data:`UNRESOLVED_BUILD_QUERY` (arguments not fully resolvable --
       skip the depth assertion for this entry) or
       :data:`INVALID_BUILD_QUERY` (arguments resolve, but the real
       implementation rejects them -- an unconditional violation). A
       call that cannot be proven to reach the real implementation at
       all -- a shadowing local ``build_query`` -- is paired with
       :data:`SHADOWED_BUILD_QUERY` instead of being reconstructed, and
       is likewise an unconditional violation.

    Rule 1 and rule 2 deliberately exclude
    ``DOCUMENTATION``/``EXAMPLES``/``RETURN``: these are YAML prose, not
    GraphQL, even though their names and content can incidentally match
    either rule's pattern.

    The remaining sets overlap by design (a named constant that also
    matches the literal pattern is reported once for each reason) -- the
    goal is coverage, not a single canonical classification.
    """
    candidates = []
    for path in sorted(_iter_python_files(root_dir)):
        try:
            source_text = open(path, encoding='utf-8').read()
        except (IOError, OSError):
            continue
        try:
            tree = ast.parse(source_text, filename=path)
        except SyntaxError:
            continue

        for name, value, lineno in _module_and_class_level_assigns(tree):
            if name in _DOC_CONSTANTS:
                continue
            if _NAME_RE.search(name):
                candidates.append(('%s:%s' % (path, name), value))

        doc_node_ids = _doc_constant_value_node_ids(tree)
        for node in ast.walk(tree):
            if isinstance(node, ast.Constant) and isinstance(node.value, str) \
                    and id(node) not in doc_node_ids:
                text = node.value
                if '{' in text and _OPERATION_LITERAL_RE.search(text):
                    lineno = getattr(node, 'lineno', '?')
                    candidates.append(('%s:%s' % (path, lineno), text))

        candidates.extend(_build_query_call_sites(tree, path))

    return candidates
