### Fetch a Lagoon token.

- name: Fetch token.
  lagoon.api.fetch_token:
    ssh_options: "-q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
  register: fetched_token
  when:
    - lagoon_api_token is not defined

- name: Extract token.
  ansible.builtin.set_fact:
    lagoon_token: '{{ fetched_token.token }}'
    lagoon_api_token: '{{ fetched_token.token }}'
  when:
    - lagoon_api_token is not defined
