### Fetch a Lagoon token.

- name: Fetch token.
  lagoon.api.token:
    ssh_options: "-q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
  register: fetched_token
  when: lagoon_api_token is not defined

- name: Extract token.
  set_fact:
    lagoon_api_token: '{{ fetched_token.token }}'
  when: lagoon_api_token is not defined
