- name: Execute an arbitratry query.
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  roles:
    - lagoon.api.common
  tasks:
    - include_role:
        name: lagoon.api.fetch_token

    - name: Query specific fields for all projects.
      lagoon.api.query:
        query: allProjects
        mainType: Project
        fields:
          - id
          - name
      register: query_results
      when: project_name is not defined

    - debug: var=query_results
      when: project_name is not defined

    - name: Query specific fields for a project.
      lagoon.api.query:
        query: projectByName
        mainType: Project
        args:
          name: '{{ project_name }}'
        fields:
          - id
          - name
          - branches
          - metadata
        subFields:
          kubernetes:
            type: Kubernetes
            fields:
              - id
              - name
      register: query_results
      when: project_name is defined

    - debug: var=query_results
      when: project_name is defined

    - name: Query variables for a project.
      lagoon.api.query:
        query: projectByName
        mainType: Project
        args:
          name: '{{ project_name }}'
        subFields:
          envVariables:
            type: EnvKeyValue
            fields:
              - id
              - name
              - value
              - scope
      register: query_results
      when: project_name is defined

    - debug: var=query_results
      when: project_name is defined
