"""Unit tests for the project module -- resource.py's golden target.

Every test drives ``run_module`` directly against a params-bearing stand-in
for ``AnsibleModule``, with ``LagoonClient.execute`` mocked at the transport
boundary. No action shim is constructed anywhere in this file: a module
handed an explicit ``lagoon_api_token`` must be fully functional on its own.

``execute`` is driven by a queue of responses rather than a single return
value, because the engine re-reads after every real mutation -- a test that
returned one fixed response would not distinguish post-mutation state from
the locally computed desired state.
"""

from __future__ import (absolute_import, division, print_function)
__metaclass__ = type

import unittest
from unittest.mock import MagicMock, patch

from ansible_collections.salsadigitalauorg.lagoon.plugins.module_utils \
    .errors import LagoonConfigError
from ansible_collections.salsadigitalauorg.lagoon.plugins.module_utils \
    .resource import camel_to_snake
from ansible_collections.salsadigitalauorg.lagoon.plugins.modules \
    .project import (
        _FIELDS,
        argument_spec,
        run_module,
    )

_ARGSPEC = argument_spec()

_MODULE_PATH = (
    'ansible_collections.salsadigitalauorg.lagoon.plugins.modules.project')

_EXISTING = {
    'id': 42,
    'name': 'my-project',
    'gitUrl': 'git@github.com:example/my-project.git',
    'productionEnvironment': 'main',
    'autoIdle': 1,
    'openshift': {'id': 2},
    'kubernetes': None,
    'autogeneratedRouteConfig': {
        'enabled': True,
        'allowPullRequests': False,
        'prefixes': [],
        'disableRequestVerification': False,
        'pathRoutes': [],
    },
}


def _existing(**overrides):
    record = dict(_EXISTING)
    record['autogeneratedRouteConfig'] = dict(
        _EXISTING['autogeneratedRouteConfig'])
    record.update(overrides)
    return record


def _make_module(state='present', check_mode=False, **params):
    """A minimal stand-in for AnsibleModule exposing only what
    run_module() reads, so this proves the module depends on nothing else
    from AnsibleModule itself.
    """
    module = MagicMock()
    module.params = {
        'lagoon_api_token': 'explicit-token',
        'lagoon_api_endpoint': 'https://api.lagoon.example.test/graphql',
        'validate_certs': True,
        'state': state,
    }
    # Every argspec option defaults to None, exactly as AnsibleModule
    # would present an unsupplied option.
    for option in _ARGSPEC:
        module.params.setdefault(option, None)
    module.params['name'] = 'my-project'
    module.params.update(params)
    module.check_mode = check_mode
    return module


class _Execute:
    """Queue-backed stand-in for LagoonClient.execute.

    Records every (document, variables) pair, and returns responses in
    order. Reads are matched by operation name so a test only has to
    supply the read results it cares about.
    """

    def __init__(self, read_results, mutation_result=None):
        self._read_results = list(read_results)
        self._mutation_result = mutation_result or {}
        self.calls = []

    def __call__(self, document, variables=None):
        self.calls.append((document, variables or {}))
        if document.startswith('query projectByName'):
            result = self._read_results.pop(0)
            return {'projectByName': result}
        return self._mutation_result

    @property
    def mutations(self):
        return [(d, v) for d, v in self.calls
                if not d.startswith('query projectByName')]

    def mutation_named(self, name):
        matches = [(d, v) for d, v in self.mutations
                   if d.startswith('mutation %s(' % name)]
        return matches

    @property
    def read_documents(self):
        return [d for d, _v in self.calls
                if d.startswith('query projectByName')]


def _run(module, read_results, mutation_result=None):
    execute = _Execute(read_results, mutation_result)
    with patch('%s.LagoonClient.execute' % _MODULE_PATH, new=execute):
        result = run_module(module)
    return result, execute


class TestCreate(unittest.TestCase):

    def test_create_calls_add_project_with_wire_names(self):
        module = _make_module(
            git_url='git@github.com:example/my-project.git',
            production_environment='main')

        result, execute = _run(
            module, [None, _existing()], {'addProject': {'id': 42}})

        self.assertTrue(result['changed'])
        added = execute.mutation_named('addProject')
        self.assertEqual(len(added), 1)
        payload = added[0][1]['input']
        self.assertEqual(payload['name'], 'my-project')
        self.assertEqual(
            payload['gitUrl'], 'git@github.com:example/my-project.git')
        self.assertEqual(payload['productionEnvironment'], 'main')

    def test_create_missing_git_url_raises_naming_the_option(self):
        """P3-D15: enforced on the create path, not via argspec required.
        The argspec assertion below is the half that would silently pass
        if someone "fixed" this by marking git_url required instead.
        """
        module = _make_module(production_environment='main')

        with self.assertRaises(LagoonConfigError) as ctx:
            _run(module, [None])

        self.assertIn('git_url', str(ctx.exception))
        self.assertNotIn(
            'required', _ARGSPEC['git_url'],
            "git_url must not be argspec-required -- the same argspec "
            "also serves update and delete")

    def test_create_missing_both_non_null_fields_names_both(self):
        module = _make_module()

        with self.assertRaises(LagoonConfigError) as ctx:
            _run(module, [None])

        message = str(ctx.exception)
        self.assertIn('git_url', message)
        self.assertIn('production_environment', message)

    def test_create_makes_no_mutation_call_when_required_missing(self):
        module = _make_module(production_environment='main')
        execute = _Execute([None])

        with patch('%s.LagoonClient.execute' % _MODULE_PATH, new=execute):
            with self.assertRaises(LagoonConfigError):
                run_module(module)

        self.assertEqual(execute.mutations, [])

    def test_create_does_not_send_update_only_fields(self):
        module = _make_module(
            git_url='git@github.com:example/my-project.git',
            production_environment='main',
            restrictions=['NO_TASKS'])

        _result, execute = _run(
            module, [None, _existing()], {'addProject': {'id': 42}})

        payload = execute.mutation_named('addProject')[0][1]['input']
        self.assertNotIn(
            'restrictions', payload,
            "restrictions is only on UpdateProjectPatchInput -- sending "
            "it to addProject would be rejected by the API")


class TestUpdate(unittest.TestCase):

    def test_update_builds_nested_id_patch_shape(self):
        """The {id, patch} wrapping is the single most regression-prone
        shape in this module: addProject is flat, updateProject is not.
        Asserted on the exact variables dict so flattening it back out
        cannot pass.
        """
        module = _make_module(auto_idle=0)

        result, execute = _run(
            module,
            [_existing(), _existing(autoIdle=0)],
            {'updateProject': {'id': 42}})

        self.assertTrue(result['changed'])
        updated = execute.mutation_named('updateProject')
        self.assertEqual(len(updated), 1)
        self.assertEqual(
            updated[0][1],
            {'input': {'id': 42, 'patch': {'autoIdle': 0}}})

    def test_update_of_hop_field_uses_flat_input_name(self):
        """openshift is Int on input but an Openshift object on output --
        the patch must carry the flat name, not the hop's shape.
        """
        module = _make_module(openshift=7)

        _result, execute = _run(
            module,
            [_existing(), _existing(openshift={'id': 7})],
            {'updateProject': {'id': 42}})

        patch_payload = execute.mutation_named(
            'updateProject')[0][1]['input']['patch']
        self.assertEqual(patch_payload, {'openshift': 7})

    def test_update_of_autogenerated_route_config_field(self):
        """autogeneratedRoutes reads from the ARC hop's `enabled` leaf but
        is patched under its own input name.
        """
        module = _make_module(autogenerated_routes=False)

        _result, execute = _run(
            module,
            [_existing(),
             _existing(autogeneratedRouteConfig=dict(
                 _EXISTING['autogeneratedRouteConfig'], enabled=False))],
            {'updateProject': {'id': 42}})

        patch_payload = execute.mutation_named(
            'updateProject')[0][1]['input']['patch']
        self.assertEqual(patch_payload, {'autogeneratedRoutes': False})

    def test_update_of_path_routes_carries_list_of_dicts(self):
        desired = [{'from_service': 'nginx', 'to_service': 'api',
                    'path': '/api'}]
        module = _make_module(autogenerated_path_routes=desired)

        _result, execute = _run(
            module,
            [_existing(),
             _existing(autogeneratedRouteConfig=dict(
                 _EXISTING['autogeneratedRouteConfig'],
                 pathRoutes=[{'fromService': 'nginx', 'toService': 'api',
                              'path': '/api'}]))],
            {'updateProject': {'id': 42}})

        patch_payload = execute.mutation_named(
            'updateProject')[0][1]['input']['patch']
        self.assertEqual(
            patch_payload, {'autogeneratedPathRoutes': desired})

    def test_path_routes_unchanged_is_a_noop(self):
        """The read flattens pathRoutes into the argspec's own key names,
        so an unchanged value must compare structurally equal and report
        no change -- otherwise every run against a project with path
        routes would report changed forever.
        """
        current = _existing(autogeneratedRouteConfig=dict(
            _EXISTING['autogeneratedRouteConfig'],
            pathRoutes=[{'fromService': 'nginx', 'toService': 'api',
                         'path': '/api'}]))
        module = _make_module(autogenerated_path_routes=[
            {'from_service': 'nginx', 'to_service': 'api', 'path': '/api'}])

        result, execute = _run(module, [current])

        self.assertFalse(result['changed'])
        self.assertEqual(execute.mutations, [])


class TestNoOp(unittest.TestCase):

    def test_no_difference_makes_no_mutation_call(self):
        module = _make_module(
            git_url='git@github.com:example/my-project.git',
            production_environment='main', auto_idle=1, openshift=2)

        result, execute = _run(module, [_existing()])

        self.assertFalse(result['changed'])
        self.assertEqual(execute.mutations, [])

    def test_unsupplied_options_do_not_force_a_change(self):
        """Only supplied options participate in the diff. An option left
        unset must never be read as "set it to null".
        """
        module = _make_module()

        result, execute = _run(module, [_existing()])

        self.assertFalse(result['changed'])
        self.assertEqual(execute.mutations, [])


class TestDelete(unittest.TestCase):

    def test_delete_uses_the_input_types_project_field(self):
        """DeleteProjectInput is {project: String!} -- verified against
        the SDL, not inferred from the mutation name.
        """
        module = _make_module(state='absent')

        result, execute = _run(
            module, [_existing()], {'deleteProject': 'success'})

        self.assertTrue(result['changed'])
        deleted = execute.mutation_named('deleteProject')
        self.assertEqual(len(deleted), 1)
        self.assertEqual(deleted[0][1], {'input': {'project': 'my-project'}})

    def test_delete_absent_already_is_a_noop(self):
        module = _make_module(state='absent')

        result, execute = _run(module, [None])

        self.assertFalse(result['changed'])
        self.assertEqual(execute.mutations, [])


class TestCheckMode(unittest.TestCase):
    """Each case runs the same scenario twice -- once for real, once under
    check mode -- and asserts the check-mode run makes zero mutation calls
    while reporting the same changed flag.
    """

    def test_check_mode_create(self):
        """Create is the one transition whose diff cannot match exactly: a
        real run re-reads and therefore reports fields the server
        defaulted, which check mode has no way to predict. What must hold
        is that check mode makes no mutation, agrees on changed, and
        predicts a subset the real run does not contradict.
        """
        params = dict(git_url='git@github.com:example/my-project.git',
                      production_environment='main')

        real_result, real_execute = _run(
            _make_module(**params), [None, _existing()],
            {'addProject': {'id': 42}})
        check_result, check_execute = _run(
            _make_module(check_mode=True, **params), [None])

        self.assertEqual(len(real_execute.mutations), 1)
        self.assertEqual(check_execute.mutations, [])
        self.assertEqual(check_result['changed'], real_result['changed'])
        self.assertIsNone(check_result['diff']['before'])
        self.assertIsNone(real_result['diff']['before'])

        real_after = real_result['diff']['after']
        for field, value in check_result['diff']['after'].items():
            self.assertIn(field, real_after)
            self.assertEqual(
                real_after[field], value,
                "check mode predicted %s=%r but the real run reported %r"
                % (field, value, real_after.get(field)))

    def test_check_mode_update(self):
        real_result, real_execute = _run(
            _make_module(auto_idle=0),
            [_existing(), _existing(autoIdle=0)],
            {'updateProject': {'id': 42}})
        check_result, check_execute = _run(
            _make_module(auto_idle=0, check_mode=True), [_existing()])

        self.assertEqual(len(real_execute.mutations), 1)
        self.assertEqual(check_execute.mutations, [])
        self.assertEqual(check_result['changed'], real_result['changed'])
        self.assertEqual(check_result['diff'], real_result['diff'])

    def test_check_mode_delete(self):
        real_result, real_execute = _run(
            _make_module(state='absent'), [_existing()],
            {'deleteProject': 'success'})
        check_result, check_execute = _run(
            _make_module(state='absent', check_mode=True), [_existing()])

        self.assertEqual(len(real_execute.mutations), 1)
        self.assertEqual(check_execute.mutations, [])
        self.assertEqual(check_result['changed'], real_result['changed'])
        self.assertEqual(check_result['diff'], real_result['diff'])


class TestCreateOnlyOrganization(unittest.TestCase):
    """P3-D16's readable clauses. Deliberately two separate tests with
    different mocks so neither path's fixture can cover for the other.
    """

    def test_organization_equal_to_current_is_a_noop_for_that_field(self):
        current = _existing(organization=3)
        module = _make_module(organization=3, auto_idle=0)

        result, execute = _run(
            module, [current, _existing(organization=3, autoIdle=0)],
            {'updateProject': {'id': 42}})

        self.assertTrue(result['changed'])
        patch_payload = execute.mutation_named(
            'updateProject')[0][1]['input']['patch']
        self.assertEqual(
            patch_payload, {'autoIdle': 0},
            "a matching create-only field must not block the rest of the "
            "update, nor appear in the patch")

    def test_organization_different_raises_naming_both_values(self):
        current = _existing(organization=3)
        module = _make_module(organization=9)

        execute = _Execute([current])
        with patch('%s.LagoonClient.execute' % _MODULE_PATH, new=execute):
            with self.assertRaises(LagoonConfigError) as ctx:
                run_module(module)

        message = str(ctx.exception)
        self.assertIn('organization', message)
        self.assertIn('3', message)
        self.assertIn('9', message)
        self.assertEqual(execute.mutations, [])


class TestCreateOnlyAddOrgOwner(unittest.TestCase):

    def test_add_org_owner_against_existing_project_always_raises(self):
        """P3-D16's unreadable clause: no readable counterpart exists, so
        convergence can never be proven and this raises regardless of
        current state.
        """
        module = _make_module(add_org_owner=True)

        execute = _Execute([_existing()])
        with patch('%s.LagoonClient.execute' % _MODULE_PATH, new=execute):
            with self.assertRaises(LagoonConfigError) as ctx:
                run_module(module)

        self.assertIn('add_org_owner', str(ctx.exception))
        self.assertEqual(execute.mutations, [])

    def test_add_org_owner_is_accepted_when_creating(self):
        module = _make_module(
            add_org_owner=True,
            git_url='git@github.com:example/my-project.git',
            production_environment='main')

        _result, execute = _run(
            module, [None, _existing()], {'addProject': {'id': 42}})

        payload = execute.mutation_named('addProject')[0][1]['input']
        self.assertTrue(payload['addOrgOwner'])


class TestCreateOnlyIdDoesNotTrip(unittest.TestCase):

    def test_unsupplied_id_never_triggers_create_only_enforcement(self):
        """id is both create-only and diff-ignored. Enforcement keys on
        supplied params, so a user who never sets it must be unaffected
        even though the existing project always has one.
        """
        module = _make_module(auto_idle=0)

        result, execute = _run(
            module, [_existing(), _existing(autoIdle=0)],
            {'updateProject': {'id': 42}})

        self.assertTrue(result['changed'])
        patch_payload = execute.mutation_named(
            'updateProject')[0][1]['input']['patch']
        self.assertNotIn('id', patch_payload)


class TestPrivateKey(unittest.TestCase):

    def test_private_key_never_appears_in_the_read_document(self):
        module = _make_module()

        _result, execute = _run(module, [_existing()])

        self.assertTrue(execute.read_documents)
        for document in execute.read_documents:
            self.assertNotIn(
                'privateKey', document,
                "privateKey must never be selected -- re-fetching key "
                "material solely to diff it is not justified")

    def test_private_key_reported_only_as_changed_without_values(self):
        module = _make_module(private_key='-----BEGIN SECRET-----')

        result, execute = _run(
            module, [_existing(), _existing()],
            {'updateProject': {'id': 42}})

        self.assertTrue(result['changed'])
        diff = result['diff']
        self.assertEqual(diff.get('changed_no_log_fields'), ['privateKey'])
        self.assertNotIn('privateKey', diff['before'] or {})
        self.assertNotIn('privateKey', diff['after'] or {})
        self.assertNotIn('BEGIN SECRET', str(diff))

    def test_private_key_is_sent_in_the_update_payload(self):
        module = _make_module(private_key='-----BEGIN SECRET-----')

        _result, execute = _run(
            module, [_existing(), _existing()],
            {'updateProject': {'id': 42}})

        patch_payload = execute.mutation_named(
            'updateProject')[0][1]['input']['patch']
        self.assertEqual(
            patch_payload['privateKey'], '-----BEGIN SECRET-----')


class TestRereadAfterMutation(unittest.TestCase):

    def test_result_reflects_post_mutation_server_state(self):
        """The server may normalise or default fields the caller never
        set, so the reported resource must come from the re-read, not from
        the locally computed desired state.
        """
        post = _existing(autoIdle=0, productionRoutes='https://normalised')
        module = _make_module(auto_idle=0)

        result, _execute = _run(
            module, [_existing(), post], {'updateProject': {'id': 42}})

        self.assertEqual(
            result['resource']['productionRoutes'], 'https://normalised')


class TestNoActionShim(unittest.TestCase):

    def test_run_module_works_with_an_explicit_token_alone(self):
        """The plugins/action boundary proof: an explicit token and no
        shim anywhere in this test.
        """
        module = _make_module(auto_idle=1,
                              lagoon_api_token='explicit-token')

        result, _execute = _run(module, [_existing()])

        self.assertFalse(result['changed'])


class TestClientConstruction(unittest.TestCase):

    def test_client_constructed_from_module_params(self):
        module = _make_module(
            lagoon_api_token='tok-123',
            lagoon_api_endpoint='https://endpoint.example.test/graphql',
            validate_certs=False)

        with patch('%s.LagoonClient' % _MODULE_PATH) as client_cls:
            client_cls.build_query = MagicMock(
                return_value='query projectByName { x }')
            client_cls.return_value.execute.return_value = {
                'projectByName': None}
            module.params['state'] = 'absent'
            run_module(module)

        call_kwargs = client_cls.call_args.kwargs
        self.assertEqual(call_kwargs['token'], 'tok-123')
        self.assertEqual(
            call_kwargs['endpoint'], 'https://endpoint.example.test/graphql')
        self.assertFalse(call_kwargs['validate_certs'])
        self.assertIs(call_kwargs['module'], module)


class TestArgspecCoversEveryWireField(unittest.TestCase):

    def test_every_wire_field_has_a_derived_argspec_option(self):
        """resource.py reads each wire field from the param whose name is
        camel_to_snake(field). An argspec that spells one differently
        makes that option silently inert -- the value is accepted, then
        dropped before it reaches the diff. Covers all 42, not a sample.
        """
        missing = [
            (field, camel_to_snake(field)) for field in _FIELDS
            if camel_to_snake(field) not in _ARGSPEC]

        self.assertEqual(
            missing, [],
            "these wire fields have no matching argspec option, so they "
            "would be silently dropped: %r" % (missing,))

    def test_argspec_has_no_option_without_a_wire_field(self):
        derived = {camel_to_snake(field) for field in _FIELDS}
        derived.add('state')

        extra = sorted(set(_ARGSPEC) - derived)

        self.assertEqual(
            extra, [],
            "these argspec options map to no wire field, so nothing "
            "would ever send them: %r" % (extra,))


if __name__ == '__main__':
    unittest.main()